# Generated by Django 4.0.6 on 2022-10-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_userdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
