# Generated by Django 4.0.6 on 2022-10-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_userdetails_id_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id_details',
        ),
    ]
