# Generated by Django 4.0.6 on 2022-10-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_userdetails_id_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='address2',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
