# Generated by Django 4.0.6 on 2022-10-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
