# Generated by Django 4.0.6 on 2022-10-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_order_customer'),
        ('authentication', '0014_remove_userdetails_customer_profile_address1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
