# Generated by Django 4.0.6 on 2022-10-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_profile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isSeller',
            field=models.BooleanField(default=False),
        ),
    ]
