# Generated by Django 4.0.6 on 2022-10-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_orderitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
