# Generated by Django 4.0.6 on 2022-09-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=10)),
                ('storage', models.CharField(max_length=10)),
                ('ram', models.CharField(max_length=10)),
                ('display_type', models.CharField(max_length=40)),
                ('display_size', models.CharField(max_length=10)),
                ('processor', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=800)),
            ],
            options={
                'verbose_name_plural': 'Mobile',
            },
        ),
    ]
