# Generated by Django 4.0.6 on 2022-10-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_mobile_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
